/**
 * Structure-aware chunking — Phase 6.
 *
 * Replaces fixed-size character splitting. A chunk is a packed run of blocks
 * inside one section; atomic blocks (tables, step lists, warnings, figures) are
 * never cut mid-unit. When an atomic block genuinely exceeds the budget it is
 * split along its OWN seams — table by rows with the header repeated, step list
 * by steps with the preamble repeated — so every part stays self-describing.
 *
 * Every chunk's embedded text is prefixed with its breadcrumb
 * ("ACS150 › Fault tracing › Fault messages generated by the drive"), which
 * costs nothing and puts the machine name and section title into both the dense
 * vector and the lexical index.
 */
import type { Block, Chunk, BlockKind, TableData } from "./model.ts";
import { breadcrumb, extractFaultCodes, extractUnits } from "./model.ts";
import { renderMarkdown } from "./tables.ts";

export interface ChunkOptions {
  /** Target size in tokens. Chunks pack up to this. */
  targetTokens?: number;
  /** Hard ceiling; an atomic block above this is split along its seams. */
  maxTokens?: number;
  machineId: string;
  machineLabel: string;
  model?: string;
  documentTitle: string;
}

const DEFAULTS = { targetTokens: 400, maxTokens: 600 };

/** Blocks that must never be split by the packer. */
const ATOMIC: BlockKind[] = ["table", "steps", "admonition", "figure"];

/**
 * Token estimate without a tokenizer dependency.
 * ~4 chars/token for English prose; tables run denser because of the pipes, so
 * we bias slightly conservative rather than overshooting the model's context.
 */
export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 3.6);
}

function isAtomic(b: Block): boolean {
  return ATOMIC.includes(b.kind);
}

function samePath(a: string[], b: string[]): boolean {
  return a.length === b.length && a.every((s, i) => s === b[i]);
}

// ---------------------------------------------------------------------------
// Splitting atomic blocks along their own seams
// ---------------------------------------------------------------------------

/** Split a table by rows, repeating the header in every part. */
export function splitTable(table: TableData, maxTokens: number): TableData[] {
  const headerMd = renderMarkdown(table.header, []);
  const headerCost = estimateTokens(headerMd);
  const parts: TableData[] = [];
  let cur: string[][] = [];
  let cost = headerCost;

  for (const row of table.rows) {
    const rowCost = estimateTokens(row.join(" | "));
    if (cur.length > 0 && cost + rowCost > maxTokens) {
      parts.push({ header: table.header, rows: cur, markdown: renderMarkdown(table.header, cur) });
      cur = [];
      cost = headerCost;
    }
    cur.push(row);
    cost += rowCost;
  }
  if (cur.length) {
    parts.push({ header: table.header, rows: cur, markdown: renderMarkdown(table.header, cur) });
  }
  return parts.length ? parts : [table];
}

/** Split a step list by steps, repeating the preamble. */
export function splitSteps(
  preamble: string,
  steps: { n: number; text: string; warnings?: string[] }[],
  maxTokens: number,
): string[] {
  const parts: string[] = [];
  const head = preamble ? `${preamble}\n` : "";
  let cur: string[] = [];
  let cost = estimateTokens(head);

  for (const s of steps) {
    const line = `${s.n}. ${s.text}${s.warnings?.length ? `\n   ⚠ ${s.warnings.join(" ")}` : ""}`;
    const c = estimateTokens(line);
    if (cur.length > 0 && cost + c > maxTokens) {
      parts.push(head + cur.join("\n"));
      cur = [];
      cost = estimateTokens(head);
    }
    cur.push(line);
    cost += c;
  }
  if (cur.length) parts.push(head + cur.join("\n"));
  return parts;
}

/** Last resort: prose that is one enormous paragraph. Split on sentence ends. */
function splitProse(text: string, maxTokens: number): string[] {
  const sentences = text.split(/(?<=[.!?])\s+/);
  const parts: string[] = [];
  let cur: string[] = [];
  let cost = 0;
  for (const s of sentences) {
    const c = estimateTokens(s);
    if (cur.length > 0 && cost + c > maxTokens) {
      parts.push(cur.join(" "));
      cur = [];
      cost = 0;
    }
    cur.push(s);
    cost += c;
  }
  if (cur.length) parts.push(cur.join(" "));
  return parts;
}

// ---------------------------------------------------------------------------
// Packing
// ---------------------------------------------------------------------------

interface Pending {
  blocks: Block[];
  texts: string[];
  tokens: number;
}

export function chunkBlocks(blocks: Block[], opts: ChunkOptions): Chunk[] {
  const targetTokens = opts.targetTokens ?? DEFAULTS.targetTokens;
  const maxTokens = opts.maxTokens ?? DEFAULTS.maxTokens;

  const chunks: Chunk[] = [];
  let pending: Pending = { blocks: [], texts: [], tokens: 0 };
  let seq = 0;

  const flush = () => {
    if (pending.blocks.length === 0) return;
    chunks.push(makeChunk(pending.blocks, pending.texts.join("\n\n"), opts, seq++));
    pending = { blocks: [], texts: [], tokens: 0 };
  };

  for (let i = 0; i < blocks.length; i++) {
    const b = blocks[i];

    // A heading starts a new chunk and leads the next one; it never trails.
    if (b.kind === "heading") {
      flush();
      pending.blocks.push(b);
      pending.texts.push(b.text);
      pending.tokens += estimateTokens(b.text);
      continue;
    }

    // Section boundary: never pack across a change of section path.
    if (pending.blocks.length > 0 && !samePath(pending.blocks[0].sectionPath, b.sectionPath)) {
      flush();
    }

    const text = blockText(b);
    const tokens = estimateTokens(text);

    // Oversized atomic block → split along its own seams into standalone parts.
    if (isAtomic(b) && tokens > maxTokens) {
      flush();
      const parts = splitAtomic(b, maxTokens);
      parts.forEach((partText, idx) => {
        chunks.push(
          makeChunk([b], partText, opts, seq++, { partIndex: idx + 1, partTotal: parts.length }),
        );
      });
      continue;
    }

    // Oversized prose → sentence split (non-atomic, so this is safe).
    if (!isAtomic(b) && tokens > maxTokens) {
      flush();
      const parts = splitProse(text, maxTokens);
      parts.forEach((partText, idx) => {
        chunks.push(
          makeChunk([b], partText, opts, seq++, { partIndex: idx + 1, partTotal: parts.length }),
        );
      });
      continue;
    }

    // Would exceed target → close the current chunk first. Atomic blocks are
    // moved whole rather than being cut to fit.
    if (pending.tokens + tokens > targetTokens && pending.blocks.length > 0) {
      flush();
    }

    pending.blocks.push(b);
    pending.texts.push(text);
    pending.tokens += tokens;
  }

  flush();
  return chunks;
}

function splitAtomic(b: Block, maxTokens: number): string[] {
  if (b.kind === "table" && b.table) {
    return splitTable(b.table, maxTokens).map((t) => t.markdown);
  }
  if (b.kind === "steps" && b.steps?.length) {
    const preamble = b.text.split("\n")[0] ?? "";
    return splitSteps(preamble, b.steps, maxTokens);
  }
  return splitProse(blockText(b), maxTokens);
}

/** The block's contribution to chunk text — tables render as markdown, warnings get a marker. */
function blockText(b: Block): string {
  if (b.kind === "table" && b.table) return b.table.markdown;
  if (b.kind === "admonition" && b.admonition) {
    return `**${b.admonition.severity.toUpperCase()}:** ${b.admonition.text}`;
  }
  if (b.kind === "figure" && b.figure) {
    const label = [b.figure.label, b.figure.caption].filter(Boolean).join(": ");
    return label ? `[Figure] ${label}` : "[Figure]";
  }
  if (b.kind === "steps" && b.steps?.length) {
    const preamble = b.text.split("\n")[0] ?? "";
    return [preamble, ...b.steps.map((s) => `${s.n}. ${s.text}`)].filter(Boolean).join("\n");
  }
  return b.text;
}

function makeChunk(
  blocks: Block[],
  body: string,
  opts: ChunkOptions,
  seq: number,
  part?: { partIndex: number; partTotal: number },
): Chunk {
  const first = blocks[0];
  const crumb = breadcrumb(opts.machineLabel, first.sectionPath);
  const suffix = part && part.partTotal > 1 ? ` (part ${part.partIndex}/${part.partTotal})` : "";
  const text = `${crumb}${suffix}\n\n${body}`;

  return {
    id: `${first.documentId}-c${String(seq).padStart(4, "0")}`,
    documentId: first.documentId,
    title: opts.documentTitle,
    text,
    charCount: text.length,
    machineId: opts.machineId,
    model: opts.model,
    sectionPath: first.sectionPath,
    pagePdf: first.pagePdf,
    pageLabel: first.pageLabel,
    blockKinds: [...new Set(blocks.map((b) => b.kind))],
    atomic: blocks.length === 1 && isAtomic(first),
    partIndex: part?.partIndex,
    partTotal: part?.partTotal,
    faultCodes: extractFaultCodes(body),
    units: extractUnits(body),
    figureRefs: blocks.flatMap((b) => (b.figure?.href ? [b.figure.href] : [])),
    textSource: blocks.some((b) => b.textSource === "ocr") ? "ocr" : first.textSource,
    blockIds: blocks.map((b) => b.id),
  };
}
