/**
 * Phase 6 verification.
 *
 * Run: node --experimental-strip-types --test packages/rag/test/chunker.test.ts
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import test from "node:test";

import { chunkBlocks, estimateTokens, splitTable } from "../src/doc/chunker.ts";
import { parseMarkdownTable } from "../src/doc/tables.ts";
import type { Block } from "../src/doc/model.ts";

const here = dirname(fileURLToPath(import.meta.url));
const fixture = readFileSync(resolve(here, "fixtures/acs150-fault-table.md"), "utf8")
  .split("\n")
  .filter((l) => !l.startsWith("#"))
  .join("\n");

const OPTS = {
  machineId: "abb-acs150",
  machineLabel: "ACS150",
  model: "ACS150",
  documentTitle: "ACS150 User Manual",
};

const SECTION = ["Fault tracing", "Fault messages generated by the drive"];

function block(p: Partial<Block> & Pick<Block, "id" | "kind" | "text">): Block {
  return {
    documentId: "abb-acs150-um",
    pagePdf: 130,
    pageLabel: "130",
    sectionPath: SECTION,
    level: 2,
    textSource: "digital",
    ...p,
  } as Block;
}

test("breadcrumb is prefixed so machine + section are inside the embedded text", () => {
  const chunks = chunkBlocks([block({ id: "b1", kind: "para", text: "Some body text." })], OPTS);
  assert.equal(chunks.length, 1);
  assert.ok(
    chunks[0].text.startsWith("ACS150 › Fault tracing › Fault messages generated by the drive"),
    `got: ${chunks[0].text.slice(0, 80)}`,
  );
  assert.ok(chunks[0].text.includes("Some body text."));
});

test("a fault table stays in ONE chunk and is marked atomic", () => {
  const table = parseMarkdownTable(fixture)!;
  const chunks = chunkBlocks(
    [block({ id: "b1", kind: "table", text: table.markdown, table })],
    { ...OPTS, maxTokens: 5000, targetTokens: 5000 },
  );
  assert.equal(chunks.length, 1);
  assert.equal(chunks[0].atomic, true);
  // Every code survived in the same chunk — no row was orphaned.
  for (const code of ["F0001", "F0002", "F0003", "F0004", "F0006", "F0007", "F0009", "F0012"]) {
    assert.ok(chunks[0].text.includes(code), `${code} missing from chunk`);
  }
});

test("an oversized table splits by rows and repeats the header in every part", () => {
  const table = parseMarkdownTable(fixture)!;
  const parts = splitTable(table, 120);
  assert.ok(parts.length > 1, "expected the table to be split");
  for (const p of parts) {
    assert.deepEqual(p.header, ["CODE", "FAULT", "CAUSE", "WHAT TO DO"]);
    assert.ok(p.markdown.includes("| CODE | FAULT | CAUSE | WHAT TO DO |"));
    assert.ok(p.rows.length > 0);
  }
  // No row lost, none duplicated.
  const total = parts.reduce((n, p) => n + p.rows.length, 0);
  assert.equal(total, table.rows.length);
});

test("split parts are labelled so a technician knows there is more", () => {
  const table = parseMarkdownTable(fixture)!;
  const chunks = chunkBlocks(
    [block({ id: "b1", kind: "table", text: table.markdown, table })],
    { ...OPTS, targetTokens: 120, maxTokens: 120 },
  );
  assert.ok(chunks.length > 1);
  assert.equal(chunks[0].partIndex, 1);
  assert.equal(chunks[0].partTotal, chunks.length);
  assert.ok(chunks[0].text.includes(`(part 1/${chunks.length})`));
  // Breadcrumb is repeated in each part, so a mid-table chunk is still self-describing.
  for (const c of chunks) assert.ok(c.text.startsWith("ACS150 › Fault tracing"));
});

test("a warning is never separated from the step it belongs to", () => {
  const blocks = [
    block({ id: "b1", kind: "para", text: "Filler. ".repeat(200) }),
    block({
      id: "b2",
      kind: "admonition",
      text: "Disconnect power before opening the drive.",
      admonition: { severity: "warning", text: "Disconnect power before opening the drive." },
    }),
  ];
  const chunks = chunkBlocks(blocks, { ...OPTS, targetTokens: 100, maxTokens: 400 });
  const warningChunk = chunks.find((c) => c.text.includes("Disconnect power"))!;
  assert.ok(warningChunk, "warning must survive");
  assert.ok(warningChunk.text.includes("**WARNING:**"), "severity must be visible to the LLM");
  assert.equal(warningChunk.blockKinds.includes("admonition"), true);
});

test("chunks never cross a section boundary", () => {
  const blocks = [
    block({ id: "b1", kind: "para", text: "Alarm text.", sectionPath: ["Fault tracing", "Alarms"] }),
    block({ id: "b2", kind: "para", text: "Fault text.", sectionPath: ["Fault tracing", "Faults"] }),
  ];
  const chunks = chunkBlocks(blocks, OPTS);
  assert.equal(chunks.length, 2);
  assert.deepEqual(chunks[0].sectionPath, ["Fault tracing", "Alarms"]);
  assert.deepEqual(chunks[1].sectionPath, ["Fault tracing", "Faults"]);
});

test("a step list is not cut mid-procedure", () => {
  const steps = Array.from({ length: 8 }, (_, i) => ({ n: i + 1, text: `Do the thing number ${i + 1}.` }));
  const chunks = chunkBlocks(
    [block({ id: "b1", kind: "steps", text: "To reset the drive:", steps })],
    { ...OPTS, targetTokens: 40, maxTokens: 400 },
  );
  // Under the max, it stays whole even though it blows the target.
  assert.equal(chunks.length, 1);
  for (let i = 1; i <= 8; i++) assert.ok(chunks[0].text.includes(`${i}. Do the thing number ${i}.`));
});

test("chunk carries the metadata retrieval and citation need", () => {
  const table = parseMarkdownTable(fixture)!;
  const [c] = chunkBlocks(
    [block({ id: "b1", kind: "table", text: table.markdown, table })],
    { ...OPTS, targetTokens: 5000, maxTokens: 5000 },
  );
  assert.equal(c.machineId, "abb-acs150");
  assert.equal(c.pageLabel, "130");
  assert.deepEqual(c.sectionPath, SECTION);
  assert.deepEqual(c.blockIds, ["b1"]);
  assert.ok(c.faultCodes.includes("F0001"));
  assert.ok(c.units.some((u) => u.includes("°C")));
  assert.equal(c.textSource, "digital");
});

test("token estimate is monotonic and non-zero", () => {
  assert.ok(estimateTokens("") === 0);
  assert.ok(estimateTokens("a".repeat(360)) === 100);
  assert.ok(estimateTokens("abc") <= estimateTokens("abcdef"));
});
