/**
 * Phase 4 verification against real ABB ACS150 content.
 *
 * Run:  node --experimental-strip-types packages/rag/test/faults.test.ts
 * (no build step, no dependencies, no API keys)
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import test from "node:test";

import { parseMarkdownTable, isFaultTable, findColumn, COL_PATTERNS } from "../src/doc/tables.ts";
import { extractFaultRecords } from "../src/doc/faults.ts";
import { extractFaultCodes, extractUnits, normalizeCode } from "../src/doc/model.ts";
import type { Block } from "../src/doc/model.ts";

const here = dirname(fileURLToPath(import.meta.url));
const fixture = readFileSync(resolve(here, "fixtures/acs150-fault-table.md"), "utf8")
  .split("\n")
  .filter((l) => !l.startsWith("#"))
  .join("\n");

function tableBlock(markdown: string): Block {
  const table = parseMarkdownTable(markdown);
  assert.ok(table, "fixture should parse as a markdown table");
  return {
    id: "acs150-b1",
    documentId: "abb-acs150-um",
    kind: "table",
    text: table.markdown,
    pagePdf: 130,
    pageLabel: "130",
    sectionPath: ["Fault tracing", "Fault messages generated by the drive"],
    level: 2,
    textSource: "digital",
    table,
  };
}

test("markdown table parses into real cells", () => {
  const t = parseMarkdownTable(fixture);
  assert.ok(t);
  assert.deepEqual(t.header, ["CODE", "FAULT", "CAUSE", "WHAT TO DO"]);
  assert.equal(t.rows[0][0], "F0001");
  assert.equal(t.rows[0][1], "OVERCURRENT");
  // The critical property: cause and action did NOT bleed into one cell.
  assert.ok(t.rows[0][2].startsWith("Output current has exceeded trip level."));
  assert.ok(t.rows[0][3].startsWith("Check motor load."));
  assert.ok(!t.rows[0][2].includes("Check motor load"), "cause must not contain the remedy");
});

test("fault table is recognised and columns are found", () => {
  const t = parseMarkdownTable(fixture)!;
  assert.equal(isFaultTable(t.header), true);
  assert.equal(findColumn(t.header, COL_PATTERNS.code), 0);
  assert.equal(findColumn(t.header, COL_PATTERNS.name), 1);
  assert.equal(findColumn(t.header, COL_PATTERNS.cause), 2);
  assert.equal(findColumn(t.header, COL_PATTERNS.action), 3);
});

test("extracts one FaultRecord per code with meaning, causes and steps", () => {
  const records = extractFaultRecords([tableBlock(fixture)], {
    machineId: "abb-acs150",
    model: "ACS150",
    documentTitle: "ACS150 User Manual",
  });

  const codes = records.map((r) => r.codeRaw).sort();
  assert.deepEqual(codes, ["F0001", "F0002", "F0003", "F0004", "F0006", "F0007", "F0009", "F0012"]);

  const f1 = records.find((r) => r.codeRaw === "F0001")!;
  assert.equal(f1.meaning, "OVERCURRENT");
  assert.equal(f1.machineId, "abb-acs150");
  assert.equal(f1.codeNorm, "f0001");
  assert.equal(f1.extraction, "table_row");
  assert.equal(f1.confidence, 1);

  // Causes: two sentences, kept apart from the remedy.
  assert.equal(f1.causes.length, 2);
  assert.match(f1.causes[0], /Output current has exceeded trip level/);

  // Steps: four imperatives, numbered, and the parenthetical parameter
  // reference must NOT have been split at its internal periods.
  assert.equal(f1.steps.length, 4);
  assert.deepEqual(
    f1.steps.map((s) => s.n),
    [1, 2, 3, 4],
  );
  assert.match(f1.steps[1].text, /parameters 2202 ACCELER TIME 1 and 2205 ACCELER TIME 2/);
});

test("provenance survives: document → section → page → block", () => {
  const [rec] = extractFaultRecords([tableBlock(fixture)], {
    machineId: "abb-acs150",
    documentTitle: "ACS150 User Manual",
  });
  assert.equal(rec.provenance.documentId, "abb-acs150-um");
  assert.equal(rec.provenance.pageLabel, "130");
  assert.equal(rec.provenance.pagePdf, 130);
  assert.deepEqual(rec.provenance.sectionPath, [
    "Fault tracing",
    "Fault messages generated by the drive",
  ]);
  assert.deepEqual(rec.provenance.blockIds, ["acs150-b1"]);
});

test("wrapped continuation row folds back into F0012 instead of becoming a ghost record", () => {
  const records = extractFaultRecords([tableBlock(fixture)], {
    machineId: "abb-acs150",
    documentTitle: "ACS150 User Manual",
  });
  assert.ok(!records.some((r) => r.codeRaw === ""), "no record without a code");

  const f12 = records.find((r) => r.codeRaw === "F0012")!;
  assert.match(f12.meaning, /MOTOR STALL/);
  // The continuation row's remedy line must have been folded in, not dropped.
  assert.equal(f12.steps.length, 2);
  assert.match(f12.steps[1].text, /Check fault function parameter settings/);
});

test("code extraction handles ABB and Schneider shapes without matching prose", () => {
  assert.deepEqual(extractFaultCodes("F0001 OVERCURRENT and F0012 MOTOR STALL"), ["F0001", "F0012"]);
  assert.deepEqual(extractFaultCodes("Drive trips on OCF or SOF"), ["OCF", "SOF"]);
  // Ordinary words and bare numbers must not become codes.
  assert.deepEqual(extractFaultCodes("Check the motor cable for damage"), []);
  assert.deepEqual(extractFaultCodes("See section Derating on page 138"), []);
  assert.equal(normalizeCode("F 0001"), "f0001");
  assert.equal(normalizeCode("f-0001"), "f0001");
});

test("measurements are indexed for keyword search", () => {
  const u = extractUnits("Fault trip limit is 135 °C and 420 V for 200 V drives, 325% of nominal");
  assert.ok(u.includes("135 °C"));
  assert.ok(u.includes("420 V"));
  assert.ok(u.includes("325 %"));
});
